before:
  hooks:
    - go mod download
    - go generate ./...

builds:
  -
    main: ./main.go

    env:
    - CGO_ENABLED=0

    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath #removes all file system paths from the compiled executable
      - -ldflags
      - '-s -w'
    goos:
      - linux
    goarch:
      - amd64
    binary: vultr-cloud-controller-manager

archives:
  -
    format: zip
    files:
      - none*
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS'
  algorithm: sha256

dockers:
  - dockerfile: Dockerfile.goreleaser
    image_templates:
      - "ghcr.io/vultr/vultr-cloud-controller-manager/vultr-cloud-controller-manager:release"
      - "ghcr.io/vultr/vultr-cloud-controller-manager/vultr-cloud-controller-manager:{{ .Tag }}"
      - "vultr/vultr-cloud-controller-manager:release"
      - "vultr/vultr-cloud-controller-manager:latest"
      - "vultr/vultr-cloud-controller-manager:{{ .Tag }}"

release:
  draft: false

changelog:
  skip: false
